const MEMORY_PROJECTS = [
	{ id: "superset", name: "superset", path: "~/Code/superset", count: 7, mark: "S" },
	{ id: "mini-krow", name: "mini-krow", path: "~/Code/mini-krow", count: 3, mark: "M" },
	{ id: "krow-app", name: "krow-app", path: "~/Code/krow-app", count: 2, mark: "K" },
];

const PROJECT_MEMORIES = [
	{
		id: "cdp",
		projectId: "superset",
		title: "Desktop CDP 必须匹配当前 worktree",
		body: "先读取当前 workspace 的 DESKTOP_VITE_PORT，再从 Electron 进程命令行确认 remote debugging port。不能默认连接 9222，也不能把其他 worktree 的 Desktop 当作等价实例。",
		category: "debugging",
		categoryLabel: "排障",
		source: "Agent",
		sourceDetail: "浏览器排障会话",
		updated: "今天 11:42",
		pinned: true,
		enabled: true,
	},
	{
		id: "cache-first",
		projectId: "superset",
		title: "Live Query 采用 cache-first 渲染",
		body: "useLiveQuery 在 collection 尚未 isReady 时也可能已经返回持久化 rows。已有 data 必须先渲染，isReady 只决定无数据时显示 loading 还是 empty。",
		category: "architecture",
		categoryLabel: "架构",
		source: "Agent",
		sourceDetail: "列表空白问题",
		updated: "昨天 18:06",
		pinned: true,
		enabled: true,
	},
	{
		id: "migration",
		projectId: "superset",
		title: "数据库 migration 的生成边界",
		body: "只修改 schema 文件，不手工编辑 drizzle 生成物，也不直接运行 migration。生成前先读取对应 app 的 migration skill 和 runbook。",
		category: "workflow",
		categoryLabel: "工作流",
		source: "手动",
		sourceDetail: "项目约定",
		updated: "8 月 30 日",
		pinned: false,
		enabled: true,
	},
	{
		id: "browser-auth",
		projectId: "superset",
		title: "本地与远程 Desktop 的 CDP 登录态不同",
		body: "setup.local.sh 使用本地 cookie flow；非本地 workspace 应通过 authClient.getSession 走内存 bearer token，不能用 raw cookie-only fetch 判断未登录。",
		category: "environment",
		categoryLabel: "环境",
		source: "Agent",
		sourceDetail: "认证链路排查",
		updated: "8 月 29 日",
		pinned: false,
		enabled: true,
	},
	{
		id: "tdd",
		projectId: "superset",
		title: "测试统一通过 Turbo 入口运行",
		body: "使用 bun run test，让 Turbo 为各 package 加载正确 preload。不要直接使用 bare bun test 跑整个 monorepo。",
		category: "workflow",
		categoryLabel: "工作流",
		source: "Agent",
		sourceDetail: "测试环境排障",
		updated: "8 月 27 日",
		pinned: false,
		enabled: true,
	},
	{
		id: "ui-language",
		projectId: "superset",
		title: "产品文案优先使用简洁中文",
		body: "UI 主体使用中文；branch、commit、worktree、Agent 等产品和代码术语保留英文。动作使用命令句，避免“成功地”等冗余词。",
		category: "preference",
		categoryLabel: "偏好",
		source: "手动",
		sourceDetail: "用户偏好",
		updated: "8 月 22 日",
		pinned: false,
		enabled: true,
	},
	{
		id: "stale",
		projectId: "superset",
		title: "旧版 Desktop 固定使用 9222",
		body: "此记录已停用，仅保留用于理解历史排障记录。",
		category: "environment",
		categoryLabel: "环境",
		source: "Agent",
		sourceDetail: "旧版本",
		updated: "7 月 11 日",
		pinned: false,
		enabled: false,
	},
	{
		id: "mini-state",
		projectId: "mini-krow",
		title: "状态机事件先落 journal 再更新 projection",
		body: "所有外部事件先追加 journal，projection 只由 reducer 推导，避免恢复时出现双写分叉。",
		category: "architecture",
		categoryLabel: "架构",
		source: "Agent",
		sourceDetail: "恢复一致性排障",
		updated: "8 月 26 日",
		pinned: true,
		enabled: true,
	},
	{
		id: "mini-run",
		projectId: "mini-krow",
		title: "本地运行命令",
		body: "使用 bun dev 启动主进程；集成测试依赖 testcontainers，首次运行需要 Docker Desktop。",
		category: "environment",
		categoryLabel: "环境",
		source: "手动",
		sourceDetail: "开发约定",
		updated: "8 月 18 日",
		pinned: false,
		enabled: true,
	},
	{
		id: "mini-api",
		projectId: "mini-krow",
		title: "Webhook 重试必须复用 delivery id",
		body: "同一次 webhook delivery 的重试必须携带原 id，服务端依赖它实现幂等写入。",
		category: "workflow",
		categoryLabel: "工作流",
		source: "Agent",
		sourceDetail: "重复事件排障",
		updated: "8 月 12 日",
		pinned: false,
		enabled: true,
	},
];

Object.assign(window, { MEMORY_PROJECTS, PROJECT_MEMORIES });
