const projects = [
	{
		id: "superset",
		name: "Superset",
		initial: "S",
		color: "#ff79c6",
		color2: "#bd93f9",
		githubOwner: "wufan17",
	},
	{
		id: "acme-web",
		name: "Acme Web",
		initial: "A",
		color: "#8be9fd",
		color2: "#50fa7b",
		githubOwner: "acme",
	},
	{
		id: "docs-marketing",
		name: "Docs & Marketing",
		initial: "D",
		color: "#f1fa8c",
		color2: "#ffb86c",
		githubOwner: "acme",
	},
	{
		id: "internal-tools",
		name: "Internal Tools",
		initial: "I",
		color: "#50fa7b",
		color2: "#8be9fd",
		githubOwner: "wufan17",
	},
	{
		id: "playground",
		name: "Playground",
		initial: "P",
		color: "#ffb86c",
		color2: "#ff5555",
		githubOwner: "wufan17",
	},
];

const workspaces = [
	// Superset — active project, multiple worktrees
	{
		id: "ws-acp-agent",
		projectId: "superset",
		name: "feat/acp-agent-control-plane",
		branch: "feat/acp-agent-control-plane",
		type: "worktree",
		status: "running",
		statusLabel: "claude · 生成 diff…",
		diff: { add: 128, del: 42 },
		pr: { number: 3891, state: "open" },
		time: "3m",
	},
	{
		id: "ws-sidebar",
		projectId: "superset",
		name: "sidebar redesign",
		branch: "wufan/sidebar-redesign",
		type: "worktree",
		status: "attention",
		statusLabel: "等待权限确认",
		diff: { add: 24, del: 6 },
		pr: null,
		time: "12m",
	},
	{
		id: "ws-catalog-cutover",
		projectId: "superset",
		name: "workspace catalog cutover",
		branch: "chore/catalog-cutover",
		type: "worktree",
		status: "ready",
		statusLabel: "构建完成 · 待 review",
		diff: { add: 312, del: 88 },
		pr: { number: 3872, state: "merged" },
		time: "1h",
	},
	{
		id: "ws-local",
		projectId: "superset",
		name: "local",
		branch: "main",
		type: "branch",
		status: "idle",
		statusLabel: "main · 干净",
		diff: null,
		pr: null,
		time: "—",
	},
	{
		id: "ws-fix-toast",
		projectId: "superset",
		name: "fix toast on empty selection",
		branch: "fix/toast-empty",
		type: "worktree",
		status: "idle",
		statusLabel: "闲置 · 昨天",
		diff: { add: 4, del: 2 },
		pr: { number: 3860, state: "draft" },
		time: "1d",
	},

	// Acme Web — one active
	{
		id: "ws-checkout",
		projectId: "acme-web",
		name: "checkout redesign",
		branch: "feat/checkout-redesign",
		type: "worktree",
		status: "running",
		statusLabel: "codex · 运行测试",
		diff: { add: 56, del: 12 },
		pr: { number: 214, state: "open" },
		time: "8m",
	},
	{
		id: "ws-cms-bugfix",
		projectId: "acme-web",
		name: "cms empty state",
		branch: "fix/cms-empty",
		type: "worktree",
		status: "idle",
		statusLabel: "闲置 · 2 天前",
		diff: { add: 8, del: 3 },
		pr: null,
		time: "2d",
	},

	// Docs & Marketing
	{
		id: "ws-changelog",
		projectId: "docs-marketing",
		name: "changelog Q3",
		branch: "docs/changelog-q3",
		type: "worktree",
		status: "idle",
		statusLabel: "闲置 · 上周",
		diff: null,
		pr: null,
		time: "5d",
	},
	{
		id: "ws-compare-pages",
		projectId: "docs-marketing",
		name: "compare pages refresh",
		branch: "marketing/compare-refresh",
		type: "worktree",
		status: "ready",
		statusLabel: "CI 已通过",
		diff: { add: 41, del: 9 },
		pr: { number: 88, state: "open" },
		time: "3h",
	},

	// Internal Tools
	{
		id: "ws-onboarding",
		projectId: "internal-tools",
		name: "onboarding checklist",
		branch: "feat/onboarding-checklist",
		type: "worktree",
		status: "idle",
		statusLabel: "闲置 · 3 天前",
		diff: { add: 14, del: 2 },
		pr: null,
		time: "3d",
	},

	// Playground
	{
		id: "ws-tests",
		projectId: "playground",
		name: "sql playground",
		branch: "exp/sql-playground",
		type: "worktree",
		status: "idle",
		statusLabel: "上次运行 · 上周",
		diff: null,
		pr: null,
		time: "7d",
	},
];

// Recent activity feed (V3)
const recentActivity = [
	"ws-acp-agent",
	"ws-checkout",
	"ws-sidebar",
	"ws-catalog-cutover",
	"ws-compare-pages",
	"ws-fix-toast",
	"ws-cms-bugfix",
];

Object.assign(window, { projects, workspaces, recentActivity });
