(function () {
	const gitHistoryFixtures = [
		{
			id: "d851a0b",
			fullHash: "d851a0b714cee88fc4dbf8d046ac1a68a9ace91",
			title: "chore(desktop): bump version to 2.0.7",
			author: "W. Fan",
			avatarName: "W. Fan",
			branch: "main",
			refs: ["main", "release/2.0"],
			group: "Today",
			time: "10:08",
			date: "Aug 23",
			lane: 0,
			kind: "chore",
			stats: { additions: 3, deletions: 1 },
			files: [
				{ dir: "apps/desktop/", file: "package.json", status: "M" },
				{ dir: "packages/host-service/", file: "package.json", status: "M" },
				{ dir: "", file: "bun.lock", status: "M" },
			],
		},
		{
			id: "2a9f18d",
			fullHash: "2a9f18d37a56799fd2763ba0e0d9af428bdc933b",
			title: "feat(acp): persist delegated execution profiles",
			author: "W. Fan",
			avatarName: "W. Fan",
			branch: "main",
			refs: ["main"],
			group: "Today",
			time: "09:39",
			date: "Aug 23",
			lane: 0,
			kind: "feat",
			stats: { additions: 126, deletions: 22 },
			files: [
				{ dir: "apps/desktop/src/renderer/", file: "I18nProvider/messages.ts", status: "M" },
				{ dir: "packages/host-service/src/runtime/acp-sessions/", file: "persistence.ts", status: "M" },
				{ dir: "packages/host-service/src/trpc/router/settings/", file: "delegated-execution.ts", status: "M" },
			],
		},
		{
			id: "a499f46",
			fullHash: "a499f46be0fb73e7dcd0fd203cb28234821d626d",
			title: "feat(ui): add provider preset icons",
			author: "W. Fan",
			avatarName: "W. Fan",
			branch: "main",
			refs: ["main"],
			group: "Today",
			time: "08:08",
			date: "Aug 23",
			lane: 0,
			kind: "feat",
			stats: { additions: 34, deletions: 2 },
			files: [
				{ dir: "packages/ui/src/assets/icons/", file: "preset-icons/index.ts", status: "M" },
				{ dir: "packages/ui/src/assets/icons/preset-icons/", file: "provider-icons.png", status: "A" },
			],
		},
		{
			id: "0f78e11",
			fullHash: "0f78e11acbf6c43e6dd98c8c5ba180bf4051fadb",
			title: "feat(desktop): ship updated provider presets",
			author: "W. Fan",
			avatarName: "W. Fan",
			branch: "feat/preset-icons",
			refs: ["feat/preset-icons"],
			group: "Yesterday",
			time: "20:45",
			date: "Aug 22",
			lane: 1,
			kind: "feat",
			stats: { additions: 18, deletions: 8 },
			files: [
				{ dir: "apps/desktop/src/renderer/lib/", file: "acp-session-launch.test.ts", status: "M" },
				{ dir: "packages/shared/src/", file: "builtin-terminal-agents.ts", status: "M" },
			],
		},
		{
			id: "00640a7",
			fullHash: "00640a76c24eb6fd8d69be0653a5044045c6b326",
			title: "feat(desktop): load ACP history by semantic turns",
			author: "A. Chen",
			avatarName: "A. Chen",
			branch: "main",
			refs: ["main"],
			group: "Yesterday",
			time: "18:01",
			date: "Aug 22",
			lane: 0,
			kind: "feat",
			stats: { additions: 42, deletions: 12 },
			files: [
				{ dir: "apps/desktop/src/renderer/screens/main/", file: "acp-pane.css", status: "M" },
				{ dir: "apps/desktop/src/renderer/screens/main/", file: "AcpTurnRail.tsx", status: "M" },
			],
		},
		{
			id: "a93ffae",
			fullHash: "a93ffaec1350192fcd2eebeb2302749ce15abfee",
			title: "feat(desktop): refine workspace run workflow",
			author: "A. Chen",
			avatarName: "A. Chen",
			branch: "feat/workspace-run",
			refs: ["feat/workspace-run"],
			group: "Yesterday",
			time: "17:26",
			date: "Aug 22",
			lane: 1,
			kind: "feat",
			stats: { additions: 88, deletions: 31 },
			files: [
				{ dir: "apps/desktop/src/renderer/routes/_local/", file: "workspace-run-start-plan.ts", status: "A" },
				{ dir: "apps/desktop/src/renderer/screens/main/components/WorkspaceView/", file: "FilesView.tsx", status: "M" },
				{ dir: "packages/ui/src/components/ai-elements/", file: "message-v2.tsx", status: "M" },
			],
		},
		{
			id: "1f96c60",
			fullHash: "1f96c601d1e83a433e0b34889e23bb7541fdaad4",
			title: "fix(desktop): restore open menu actions",
			author: "J. Lin",
			avatarName: "J. Lin",
			branch: "main",
			refs: ["main"],
			group: "Yesterday",
			time: "16:02",
			date: "Aug 22",
			lane: 0,
			kind: "fix",
			stats: { additions: 21, deletions: 9 },
			files: [
				{ dir: "apps/desktop/src/lib/trpc/routers/external/", file: "index.ts", status: "M" },
				{ dir: "packages/ui/src/components/ui/", file: "dropdown-menu.tsx", status: "M" },
			],
		},
		{
			id: "be52fd1",
			fullHash: "be52fd1775774671034c34a8e1bf4ba2dd52b51f",
			title: "chore(desktop): bump version to 2.0.6",
			author: "W. Fan",
			avatarName: "W. Fan",
			branch: "main",
			refs: ["main", "release/2.0"],
			group: "Earlier",
			time: "17:17",
			date: "Aug 21",
			lane: 0,
			kind: "chore",
			stats: { additions: 4, deletions: 2 },
			files: [
				{ dir: "apps/desktop/", file: "package.json", status: "M" },
				{ dir: "packages/host-service/", file: "package.json", status: "M" },
			],
		},
		{
			id: "915ced1",
			fullHash: "915ced1b1ff2d7fcf831cdc41b6e072dd702d1fc",
			title: "chore(agents): hide unavailable preset",
			author: "J. Lin",
			avatarName: "J. Lin",
			branch: "main",
			refs: ["main"],
			group: "Earlier",
			time: "15:17",
			date: "Aug 21",
			lane: 0,
			kind: "chore",
			stats: { additions: 12, deletions: 6 },
			files: [
				{ dir: "packages/shared/src/", file: "agent-catalog.ts", status: "M" },
				{ dir: "packages/shared/src/", file: "host-agent-presets.ts", status: "A" },
			],
		},
		{
			id: "9dfaef9",
			fullHash: "9dfaef96eaf6fbceb0f32ebca6533978efe120b7",
			title: "fix(desktop): quiet background status notifications",
			author: "A. Chen",
			avatarName: "A. Chen",
			branch: "main",
			refs: ["main"],
			group: "Earlier",
			time: "15:37",
			date: "Aug 21",
			lane: 0,
			kind: "fix",
			stats: { additions: 16, deletions: 11 },
			files: [
				{ dir: "apps/desktop/src/renderer/screens/main/components/", file: "StatusIndicator.tsx", status: "M" },
				{ dir: "packages/host-service/src/runtime/acp-sessions/", file: "pi-acp-bundle.ts", status: "M" },
			],
		},
	];

	Object.assign(window, { gitHistoryFixtures });
})();
