import { Button } from "@superset/ui/button";
import {
	Collapsible,
	CollapsibleContent,
	CollapsibleTrigger,
} from "@superset/ui/collapsible";
import {
	Command,
	CommandEmpty,
	CommandInput,
	CommandItem,
	CommandList,
} from "@superset/ui/command";
import { Input } from "@superset/ui/input";
import { Label } from "@superset/ui/label";
import { Popover, PopoverContent, PopoverTrigger } from "@superset/ui/popover";
import { Switch } from "@superset/ui/switch";
import { GoGitBranch } from "react-icons/go";
import {
	HiCheck,
	HiChevronDown,
	HiChevronUpDown,
	HiOutlinePencil,
} from "react-icons/hi2";
import { formatRelativeTime } from "renderer/lib/formatRelativeTime";
import { useTranslation } from "renderer/providers/I18nProvider";

interface PromptGroupAdvancedOptionsProps {
	showAdvanced: boolean;
	onShowAdvancedChange: (open: boolean) => void;
	branchInputValue: string;
	onBranchInputChange: (value: string) => void;
	onBranchInputBlur: () => void;
	onEditPrefix: () => void;
	runSetupScript: boolean;
	onRunSetupScriptChange: (checked: boolean) => void;
	shortcutHint?: string;
	hideSetupScript?: boolean;
	isBranchesError?: boolean;
	isBranchesLoading?: boolean;
	compareBaseBranchOpen?: boolean;
	onCompareBaseBranchOpenChange?: (open: boolean) => void;
	effectiveCompareBaseBranch?: string | null;
	defaultBranch?: string;
	branchSearch?: string;
	onBranchSearchChange?: (search: string) => void;
	filteredBranches?: Array<{ name: string; lastCommitDate: number }>;
	onSelectCompareBaseBranch?: (branchName: string) => void;
}

export function PromptGroupAdvancedOptions({
	showAdvanced,
	onShowAdvancedChange,
	branchInputValue,
	onBranchInputChange,
	onBranchInputBlur,
	onEditPrefix,
	runSetupScript,
	onRunSetupScriptChange,
	shortcutHint,
	hideSetupScript,
	isBranchesError,
	isBranchesLoading,
	compareBaseBranchOpen,
	onCompareBaseBranchOpenChange,
	effectiveCompareBaseBranch,
	defaultBranch,
	branchSearch,
	onBranchSearchChange,
	filteredBranches,
	onSelectCompareBaseBranch,
}: PromptGroupAdvancedOptionsProps) {
	const { t } = useTranslation();
	const showCompareBaseBranch = onCompareBaseBranchOpenChange != null;

	const relativeTimeLabels = {
		now: t("time.now"),
		second: t("time.secondShort"),
		minute: t("time.minuteShort"),
		hour: t("time.hourShort"),
		day: t("time.dayShort"),
		month: t("time.monthShort"),
	};

	return (
		<Collapsible open={showAdvanced} onOpenChange={onShowAdvancedChange}>
			<div className="flex items-center justify-between">
				<CollapsibleTrigger className="flex items-center gap-1 text-xs text-fg-mute hover:text-fg transition-colors">
					<HiChevronDown
						className={`size-3 transition-transform ${showAdvanced ? "" : "-rotate-90"}`}
					/>
					{t("workspace.advancedOptions")}
				</CollapsibleTrigger>
				{shortcutHint && (
					<span className="text-[11px] text-fg-faint">
						{shortcutHint}
					</span>
				)}
			</div>
			<CollapsibleContent className="pt-3 space-y-3">
				<div className="space-y-1.5">
					<div className="flex items-center justify-between">
						<label htmlFor="branch" className="text-xs text-fg-mute">
							{t("workspace.branchName")}
						</label>
						<button
							type="button"
							onClick={onEditPrefix}
							className="inline-flex items-center gap-1 text-xs text-fg-mute hover:text-fg transition-colors"
						>
							<HiOutlinePencil className="size-3" />
							<span>{t("workspace.editPrefix")}</span>
						</button>
					</div>
					<Input
						id="branch"
						className="h-8 text-sm font-mono"
						placeholder={t("workspace.autoGenerated")}
						value={branchInputValue}
						onChange={(event) => onBranchInputChange(event.target.value)}
						onBlur={onBranchInputBlur}
					/>
				</div>

				{showCompareBaseBranch && (
					<div className="space-y-1.5">
						<span className="text-xs text-fg-mute">
							{t("project.baseBranch")}
						</span>
						{isBranchesError ? (
							<div className="flex items-center gap-2 h-8 px-3 rounded-ds-3 border border-destructive/50 bg-destructive/10 text-destructive text-xs">
								{t("workspace.failedLoadBranches")}
							</div>
						) : (
							<Popover
								open={compareBaseBranchOpen}
								onOpenChange={onCompareBaseBranchOpenChange}
								modal={false}
							>
								<PopoverTrigger asChild>
									<Button
										variant="outline"
										size="sm"
										className="w-full h-8 justify-between font-normal"
										disabled={isBranchesLoading}
									>
										<span className="flex items-center gap-2 truncate">
											<GoGitBranch className="size-3.5 shrink-0 text-fg-mute" />
											<span className="truncate font-mono text-sm">
												{effectiveCompareBaseBranch ||
													t("workspace.selectBaseBranch")}
											</span>
											{effectiveCompareBaseBranch === defaultBranch && (
												<span className="text-[10px] text-fg-mute bg-hover px-1.5 py-0.5 rounded">
													{t("workspace.defaultBranch")}
												</span>
											)}
										</span>
										<HiChevronUpDown className="size-4 shrink-0 text-fg-mute" />
									</Button>
								</PopoverTrigger>
								<PopoverContent
									className="w-[--radix-popover-trigger-width] p-0"
									align="start"
									onWheel={(event) => event.stopPropagation()}
								>
									<Command shouldFilter={false}>
										<CommandInput
											placeholder={t("workspace.searchBranches")}
											value={branchSearch}
											onValueChange={onBranchSearchChange}
										/>
										<CommandList className="max-h-[200px]">
											<CommandEmpty>{t("workspace.noBranches")}</CommandEmpty>
											{filteredBranches?.map((branch) => (
												<CommandItem
													key={branch.name}
													value={branch.name}
													onSelect={() =>
														onSelectCompareBaseBranch?.(branch.name)
													}
													className="flex items-center justify-between"
												>
													<span className="flex items-center gap-2 truncate">
														<GoGitBranch className="size-3.5 shrink-0 text-fg-mute" />
														<span className="truncate">{branch.name}</span>
														{branch.name === defaultBranch && (
															<span className="text-[10px] text-fg-mute bg-hover px-1.5 py-0.5 rounded">
																{t("workspace.defaultBranch")}
															</span>
														)}
													</span>
													<span className="flex items-center gap-2 shrink-0">
														{branch.lastCommitDate > 0 && (
															<span className="text-xs text-fg-mute">
																{formatRelativeTime(
																	branch.lastCommitDate,
																	relativeTimeLabels,
																)}
															</span>
														)}
														{effectiveCompareBaseBranch === branch.name && (
															<HiCheck className="size-4 text-accent-solid" />
														)}
													</span>
												</CommandItem>
											))}
										</CommandList>
									</Command>
								</PopoverContent>
							</Popover>
						)}
					</div>
				)}

				{!hideSetupScript && (
					<div className="flex items-center justify-between">
						<Label
							htmlFor="run-setup-script"
							className="text-xs text-fg-mute"
						>
							{t("workspace.runSetupScript")}
						</Label>
						<Switch
							id="run-setup-script"
							checked={runSetupScript}
							onCheckedChange={onRunSetupScriptChange}
						/>
					</div>
				)}
			</CollapsibleContent>
		</Collapsible>
	);
}
