const { FullAppV4Icon: AppFullV4Icon, FullAppV4Toast: AppFullV4Toast, FullAppV4Sidebar: AppFullV4Sidebar, FullAppV4Changes: AppFullV4Changes } = window.FullAppV4Parts;
const { sidebarProjectData: appFullV4Projects } = window.SidebarHierarchyData;

function SidebarFullAppV4() {
  const [selectedWorkspaceId, setSelectedWorkspaceId] = React.useState("superset-local");
  const [openProjectIds, setOpenProjectIds] = React.useState(appFullV4Projects.map((project) => project.id));
  const [changeTab, setChangeTab] = React.useState("Changes");
  const [toastCopy, setToastCopy] = React.useState("");
  const [composerValue, setComposerValue] = React.useState("请检查 workspace 切换后 Changes 里的文件列表是否仍然准确。");
  const selectedWorkspace = appFullV4Projects.flatMap((project) => project.workspaces).find((workspace) => workspace.id === selectedWorkspaceId) || appFullV4Projects[0].workspaces[0];

  React.useEffect(() => { if (!toastCopy) return undefined; const fullAppV4Timer = window.setTimeout(() => setToastCopy(""), 2200); return () => window.clearTimeout(fullAppV4Timer); }, [toastCopy]);
  const toggleProject = (projectId) => setOpenProjectIds((previousIds) => previousIds.includes(projectId) ? previousIds.filter((currentId) => currentId !== projectId) : [...previousIds, projectId]);
  const selectWorkspace = (workspace) => { setSelectedWorkspaceId(workspace.id); setToastCopy(`已切换到 ${workspace.title}`); };
  const sendMessage = () => { if (!composerValue.trim()) return; setToastCopy("已发送消息"); setComposerValue(""); };

  return <main className="v4-app" data-screen-label="Sidebar Full App v4">
    <header className="v4-chrome"><div className="v4-lights" aria-label="Window controls"><i className="v4-light red"></i><i className="v4-light yellow"></i><i className="v4-light green"></i></div><div className="v4-tabs"><button className="v4-tab is-current" type="button"><AppFullV4Icon name="branch" size={11} /><span>{selectedWorkspace.branch}</span></button><button className="v4-tab" type="button"><AppFullV4Icon name="branch" size={11} /><span>main</span></button><button className="v4-tab" type="button"><AppFullV4Icon name="plus" size={11} /><span>New workspace</span></button></div><div className="v4-chrome-actions"><button className="v4-icon-button" type="button" aria-label="Refresh"><AppFullV4Icon name="refresh" size={13} /></button><button className="v4-icon-button" type="button" aria-label="More"><AppFullV4Icon name="moreH" size={13} /></button></div></header>
    <div className="v4-body"><nav className="v4-rail" aria-label="Primary navigation"><div className="v4-rail-top"><button className="v4-nav-item is-active" type="button" aria-label="Workspaces"><AppFullV4Icon name="branch" size={16} /></button><button className="v4-nav-item" type="button" aria-label="Changes" onClick={() => setChangeTab("Changes")}><AppFullV4Icon name="changes" size={16} /></button><button className="v4-nav-item" type="button" aria-label="Search" onClick={() => setToastCopy("已打开 Command palette")}><AppFullV4Icon name="search" size={16} /></button></div><div className="v4-rail-bottom"><button className="v4-nav-item" type="button" aria-label="Settings"><AppFullV4Icon name="moreH" size={16} /></button></div></nav><AppFullV4Sidebar selectedWorkspaceId={selectedWorkspaceId} openProjectIds={openProjectIds} onToggle={toggleProject} onSelect={selectWorkspace} onToast={setToastCopy} />
      <section className="v4-main"><header className="v4-workspace-header"><div className="v4-crumb"><b>superset</b> / {selectedWorkspace.title} <span style={{ color: "var(--fg-faint)" }}>·</span> {selectedWorkspace.branch}</div><div className="v4-header-actions"><span className="v4-running"><i></i>running</span><button className="v4-icon-button" type="button" aria-label="Open terminal" onClick={() => setToastCopy("已打开 terminal")}><AppFullV4Icon name="terminal" size={13} /></button><button className="v4-icon-button" type="button" aria-label="Workspace menu"><AppFullV4Icon name="moreH" size={13} /></button></div></header>
        <div className="v4-conversation"><div className="v4-thread"><article className="v4-message user"><span className="v4-message-mark">WF</span><div><div className="v4-message-meta">You <small>14:03</small></div><div className="v4-message-body"><p>把项目与 workspace 的层级在 desktop sidebar 里收紧：项目之间留白，workspace 只靠缩进和选中状态表达。</p></div></div></article><article className="v4-message"><span className="v4-message-mark">K</span><div><div className="v4-message-meta">Kro <small>14:04 · Opus 5</small></div><div className="v4-message-body"><p>我会保持项目名作为纯文本锚点，不加入头像或缩略图；当前 workspace 使用全宽的 <code>accent tint</code> 与 2px 左条。</p></div><div className="v4-tool"><div className="v4-tool-head"><AppFullV4Icon name="search" size={12} /><strong>Grep</strong><span className="v4-tool-path">WorkspaceSidebar</span><span className="v4-tool-state">exit 0</span></div><div className="v4-tool-body">apps/desktop/src/renderer/screens/main/WorkspaceSidebar.tsx:42\napps/desktop/src/renderer/screens/main/ChatInterface.tsx:118</div></div><div className="v4-message-body" style={{ marginTop: "var(--s-4)" }}><p>已把选择同步到 workspace header 和 Changes 面板。项目可以收起，<code>+</code> 会保留当前项目上下文。</p></div></div></article></div></div>
        <div className="v4-composer-wrap"><div className="v4-composer"><textarea aria-label="Message Kro" value={composerValue} onChange={(event) => setComposerValue(event.target.value)} placeholder="Ask Kro to make a change…"></textarea><div className="v4-composer-actions"><button className="v4-icon-button" type="button" aria-label="Attach file"><AppFullV4Icon name="plus" size={13} /></button><span className="v4-composer-label"><i></i>Kro · Opus 5</span><span style={{ flex: 1 }}></span><button className="v4-send" type="button" onClick={sendMessage}><AppFullV4Icon name="arrowRight" size={12} />Send</button></div></div></div>
      </section><AppFullV4Changes selectedWorkspace={selectedWorkspace} activeTab={changeTab} onTabChange={setChangeTab} onToast={setToastCopy} /></div>
    <footer className="v4-status"><span className="ok">connected · host-service :5881</span><span><AppFullV4Icon name="branch" size={11} />{selectedWorkspace.branch}</span><span className="warn">6 files unstaged</span><span className="spacer">Opus 5 · 200k ctx</span><span>UTC+8 · 14:08</span></footer>
    {toastCopy ? <div className="v4-toast"><AppFullV4Toast tone="info">{toastCopy}</AppFullV4Toast></div> : null}
  </main>;
}

ReactDOM.createRoot(document.getElementById("root")).render(<SidebarFullAppV4 />);
