const { Icon: BranchPickerV6Icon, Toast: BranchPickerV6Toast, ContextMenu: BranchPickerV6ContextMenu, MenuHeading: BranchPickerV6MenuHeading, MenuSep: BranchPickerV6MenuSep, MenuGroup: BranchPickerV6MenuGroup, MenuItem: BranchPickerV6MenuItem, Popover: BranchPickerV6Popover, PopoverHeader: BranchPickerV6PopoverHeader, PopoverGroup: BranchPickerV6PopoverGroup, PopoverRow: BranchPickerV6PopoverRow, PopoverSep: BranchPickerV6PopoverSep, PopoverHint: BranchPickerV6PopoverHint, Kbd: BranchPickerV6Kbd } = window.SupersetDesignSystem_91a6da;

const branchPickerV6Files = [
  { path: "apps/desktop/src/renderer/screens/main/WorkspaceSidebar.tsx", state: "M", tone: "mod" },
  { path: "apps/desktop/src/renderer/screens/main/ChatInterface.tsx", state: "M", tone: "mod" },
  { path: "apps/desktop/src/renderer/hooks/useWorkspace.ts", state: "A", tone: "add" },
  { path: "packages/ui/src/components/ui/tabs.tsx", state: "M", tone: "mod" },
  { path: "designs/sidebar-project-workspace-hierarchy/Sidebar Branch Picker v6.html", state: "A", tone: "add" }
];
const branchPickerV6Branches = { local: ["feat/sidebar-hierarchy", "main", "feat/kro-suite", "fix/desktop-menu"], remote: ["origin/feat/sidebar-hierarchy", "origin/release/2026-08", "origin/main"] };

function BranchPickerV6Project({ project, selectedWorkspaceId, branchFor, onSelect, onMenu }) {
  return <section className="v6-project"><div className="v6-project-head"><button className="v6-project-name" type="button">{project.title}</button><span className="v6-project-count">{project.workspaces.length}</span><button className="v6-icon-button" type="button" aria-label={`在 ${project.title} 新建 workspace`}><BranchPickerV6Icon name="plus" size={13} /></button><button className="v6-icon-button" type="button" aria-label={`展开 ${project.title}`}><BranchPickerV6Icon name="chevron" size={12} /></button></div>{project.workspaces.map((workspace) => <div key={workspace.id} className={`v6-workspace${workspace.id === selectedWorkspaceId ? " active" : ""}`}><button className="v6-workspace-copy" type="button" onClick={() => onSelect(workspace)}><span className="v6-workspace-title">{workspace.title}</span><span className="v6-workspace-branch">{branchFor(workspace)}</span></button><button className="v6-workspace-more" type="button" aria-label={`${branchFor(workspace)} 的 branch 操作`} onClick={(clickEvent) => onMenu(workspace, clickEvent.currentTarget)}><BranchPickerV6Icon name="moreH" size={14} /></button></div>)}</section>;
}

function BranchPickerV6Sidebar({ projects, selectedWorkspaceId, branchFor, onSelect, onMenu, onToast }) {
  return <aside className="v6-sidebar" aria-label="Projects and workspaces"><div className="v6-side-head"><span className="v6-side-title">Workspaces</span><span className="v6-icon-row"><button className="v6-icon-button" type="button" aria-label="Search workspaces" onClick={() => onToast("已打开 workspace 搜索")}><BranchPickerV6Icon name="search" size={13} /></button><button className="v6-icon-button" type="button" aria-label="Workspace settings"><BranchPickerV6Icon name="moreH" size={13} /></button></span></div><div className="v6-projects">{projects.map((project) => <BranchPickerV6Project key={project.id} project={project} selectedWorkspaceId={selectedWorkspaceId} branchFor={branchFor} onSelect={onSelect} onMenu={onMenu} />)}</div><div className="v6-side-foot"><button className="v6-add" type="button" onClick={() => onToast("已打开 Add repository")}><BranchPickerV6Icon name="plus" size={13} />Add repository</button><button className="v6-icon-button" type="button" aria-label="Settings"><BranchPickerV6Icon name="moreH" size={13} /></button></div></aside>;
}

function BranchPickerV6Changes({ activeTab, onTabChange, onToast }) {
  const shownFiles = activeTab === "Files" ? branchPickerV6Files.slice(0, 3) : branchPickerV6Files;
  return <aside className="v6-changes" aria-label="Changes panel"><div className="v6-change-tabs"><button className={`v6-change-tab${activeTab === "Changes" ? " active" : ""}`} type="button" onClick={() => onTabChange("Changes")}>Changes</button><button className={`v6-change-tab${activeTab === "Files" ? " active" : ""}`} type="button" onClick={() => onTabChange("Files")}>Files</button><span style={{ flex: 1 }}></span><button className="v6-icon-button" type="button" aria-label="Refresh changes" onClick={() => onToast("已刷新 changes")}><BranchPickerV6Icon name="refresh" size={13} /></button></div><div className="v6-files">{shownFiles.map((file) => { const fileParts = file.path.split("/"); const fileName = fileParts.pop(); return <button key={file.path} type="button" className="v6-file" onClick={() => onToast(`已打开 ${fileName}`)}><BranchPickerV6Icon name="file" size={12} /><span className="v6-file-path"><span>{fileParts.join("/")}/</span>{fileName}</span><span className={`v6-state ${file.tone}`}>{file.state}</span></button>; })}</div><div className="v6-commit"><input aria-label="Commit message" defaultValue="refactor(workspaces): keep branch picker in place" /><button type="button" onClick={() => onToast("已提交并推送更改")}>Commit &amp; Push</button></div></aside>;
}

function BranchPickerV6Actions({ workspace, anchor, onPick, onAction }) {
  const menuTop = Math.min(anchor.top - 4, window.innerHeight - 446); const menuLeft = Math.min(anchor.right + 8, window.innerWidth - 282);
  const runAction = (copy) => () => onAction(copy);
  return <div className="v6-overlay" style={{ top: menuTop, left: menuLeft }} onMouseDown={(mouseEvent) => mouseEvent.stopPropagation()}><BranchPickerV6ContextMenu><BranchPickerV6MenuHeading title={workspace.branch} badge={<span className="tag">当前</span>} /><div className="v6-menu-note">workspace · {workspace.title}</div><BranchPickerV6MenuSep /><BranchPickerV6MenuGroup>常用</BranchPickerV6MenuGroup><BranchPickerV6MenuItem iconName="arrowRight" label="切换分支…" onClick={onPick} /><BranchPickerV6MenuItem iconName="plus" label="从此分支新建 workspace…" onClick={runAction(`已从 ${workspace.branch} 新建 workspace`)} /><BranchPickerV6MenuGroup>同步</BranchPickerV6MenuGroup><BranchPickerV6MenuItem iconName="refresh" label="Fetch" onClick={runAction("已 fetch origin")} /><BranchPickerV6MenuItem iconName="pull" label="Pull" onClick={runAction("已拉取当前分支")} /><BranchPickerV6MenuItem iconName="push" label="Push" onClick={runAction("已推送当前分支")} /><BranchPickerV6MenuGroup>管理</BranchPickerV6MenuGroup><BranchPickerV6MenuItem iconName="copy" label="复制分支名" onClick={runAction(`已复制 · ${workspace.branch}`)} /><BranchPickerV6MenuItem iconName="edit" label="重命名分支…" onClick={runAction("已打开重命名分支")} /><BranchPickerV6MenuItem iconName="branch" label="打开 Pull Request" onClick={runAction("已打开 Pull Request")} /><BranchPickerV6MenuSep /><BranchPickerV6MenuItem iconName="trash" label="删除分支" danger disabled title="不能删除当前分支" /></BranchPickerV6ContextMenu></div>;
}

function BranchPickerV6Picker({ workspace, anchor, onBack, onChoose }) {
  const [query, setQuery] = React.useState(""); const pickerInputRef = React.useRef(null);
  React.useEffect(() => { window.setTimeout(() => pickerInputRef.current && pickerInputRef.current.focus(), 0); }, []);
  const matchBranch = (branchName) => branchName.toLowerCase().includes(query.trim().toLowerCase()); const localBranches = [...new Set([workspace.branch, ...branchPickerV6Branches.local])].filter(matchBranch); const remoteBranches = branchPickerV6Branches.remote.filter(matchBranch);
  const menuTop = Math.min(anchor.top - 4, window.innerHeight - 446); const menuLeft = Math.min(anchor.right + 8, window.innerWidth - 282); const firstResult = localBranches[0] || remoteBranches[0]; const chooseFirstResult = (keyboardEvent) => { if (keyboardEvent.key !== "Enter" || !firstResult) return; keyboardEvent.preventDefault(); onChoose(firstResult.replace("origin/", "")); };
  return <div className="v6-overlay" style={{ top: menuTop, left: menuLeft }} onMouseDown={(mouseEvent) => mouseEvent.stopPropagation()} onKeyDown={chooseFirstResult}><BranchPickerV6Popover><div className="v6-picker-head"><button className="v6-picker-back" type="button" aria-label="返回 branch 操作" onClick={onBack}><BranchPickerV6Icon name="arrowRight" size={13} style={{ transform: "rotate(180deg)" }} /></button><span>切换分支</span></div><BranchPickerV6PopoverHeader placeholder="搜索 branch…" value={query} onChange={setQuery} inputRef={pickerInputRef} trailing={<BranchPickerV6Kbd>⌘K</BranchPickerV6Kbd>} /><div className="v6-picker-list"><BranchPickerV6PopoverGroup label="本地分支" count={localBranches.length} />{localBranches.map((branchName) => <BranchPickerV6PopoverRow key={branchName} name={branchName} current={branchName === workspace.branch} focused={branchName === firstResult} tag={branchName === workspace.branch ? <span className="v6-current-tag">当前</span> : null} end={branchName === "main" ? "↓ 2" : branchName === "feat/kro-suite" ? "↑ 3" : null} onClick={() => onChoose(branchName)} />)}<BranchPickerV6PopoverSep /><BranchPickerV6PopoverGroup label="远程分支" count={remoteBranches.length} />{remoteBranches.map((branchName) => <BranchPickerV6PopoverRow key={branchName} iconName="cloud" name={branchName} focused={!localBranches.length && branchName === firstResult} end="origin" onClick={() => onChoose(branchName.replace("origin/", ""))} />)}{!localBranches.length && !remoteBranches.length ? <div className="v6-menu-note">没有匹配的 branch</div> : null}</div><BranchPickerV6PopoverHint><BranchPickerV6Kbd>Esc</BranchPickerV6Kbd>关闭 <span style={{ marginLeft: "auto" }}><BranchPickerV6Kbd>Enter</BranchPickerV6Kbd>切换</span></BranchPickerV6PopoverHint></BranchPickerV6Popover></div>;
}

window.BranchPickerV6Parts = { BranchPickerV6Icon, BranchPickerV6Toast, BranchPickerV6Sidebar, BranchPickerV6Changes, BranchPickerV6Actions, BranchPickerV6Picker };
