import type { Theme } from "../types";

/**
 * Dracula Colorful — a cooler, high-contrast interpretation of Dracula.
 * Pink is used as the signature accent while blue-grey anchors larger surfaces.
 */
export const draculaColorfulTheme: Theme = {
	id: "dracula-colorful",
	name: "Dracula Colorful",
	author:
		"Dracula Theme (palette) / adapted for Superset — authentic blue-grey accent with pink decorations",
	description:
		"Dracula palette faithful to the original: cool blue-purple base and blue-grey accent line (like Dracula's #44475a selection color), lifted for modern readability. Pink is signature but scattered as many small decorations (left rails, dirty dots, active icons, cursors, focus rings, tab underlines, badges) rather than large-area fills — so pink is present on every screen without ever becoming muddy or cheap.",
	type: "dark",
	isBuiltIn: true,

	ui: {
		background: "#2f3244",
		foreground: "#f2f4ff",
		card: "#3a3e56",
		cardForeground: "#f2f4ff",
		popover: "#3a3e56",
		popoverForeground: "#f2f4ff",
		primary: "#ff8fd1",
		primaryForeground: "#ffe4f2",
		secondary: "#4c5075",
		secondaryForeground: "#f2f4ff",
		muted: "#3f4560",
		mutedForeground: "#a2b0d8",
		accent: "#4c5075",
		accentForeground: "#f2f4ff",
		tertiary: "#3a3e56",
		tertiaryActive: "#575d80",
		destructive: "#ff7c7c",
		destructiveForeground: "#f2f4ff",
		border: "#525777",
		input: "#464b68",
		ring: "#ff8fd1",
		sidebar: "#3a3e56",
		sidebarForeground: "#f2f4ff",
		sidebarPrimary: "#ff8fd1",
		sidebarPrimaryForeground: "#ffe4f2",
		sidebarAccent: "#4c5075",
		sidebarAccentForeground: "#f2f4ff",
		sidebarBorder: "#525777",
		sidebarRing: "#ff8fd1",
		chart1: "#ff8fd1",
		chart2: "#6fff95",
		chart3: "#a0f0ff",
		chart4: "#f6ff9a",
		chart5: "#c4a2ff",
		highlightMatch: "#ff8fd166",
		highlightActive: "#ffc47a66",
		highlight: "#ff8fd1",
		highlightForeground: "#ffe4f2",
	},

	terminal: {
		background: "#2f3244",
		foreground: "#f2f4ff",
		cursor: "#ff8fd1",
		cursorAccent: "#2f3244",
		selectionBackground: "#4c5075",
		black: "#3a3e56",
		red: "#ff6e6e",
		green: "#6fff95",
		yellow: "#f6ff9a",
		blue: "#c4a2ff",
		magenta: "#ff8fd1",
		cyan: "#a0f0ff",
		white: "#f2f4ff",
		brightBlack: "#a2b0d8",
		brightRed: "#ff9494",
		brightGreen: "#8fffab",
		brightYellow: "#ffffb8",
		brightBlue: "#dcc4ff",
		brightMagenta: "#ffaee0",
		brightCyan: "#c0f6ff",
		brightWhite: "#ffffff",
	},
};
